from c2m2_assessment.fairshake.rubric import Rubric

rubric = Rubric()
rubric.metric('c2m2_assessment.metrics.m_fairshake_104_persistent_identifier.metric')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_1')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_2')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_3')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_4')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_5')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_6')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_8')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_9')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_10')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_11')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_12')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_13')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_14')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_15')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_16')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_17')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_18')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_19')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_20')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_21')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_22')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_23')
rubric.metric('c2m2_assessment.rubrics.NCE.m_cfde_fair_24')
